version: '3.8'

services:
  nginx:
    build: ./nginx
    image: docker-tor-nginx:latest
    deploy:
      mode: global

  tor:
    build:
      context: ./tor
      args:
        DOCKER_PORT: ${DOCKER_PORT}
    image: docker-tor-tor:latest
    env_file: settings.env
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"

volumes:
  data_dir:
